Fix: Correct activation hook to use instance method instead of static
The activate() method in the KataWP class is not static, but we were trying to call it statically through register_activation_hook.

Error: TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method KataWP::activate() cannot be called statically

Solution: Changed the activation hook from:
register_activation_hook(KATAWP_PLUGIN_FILE, array('KataWP', 'activate'));

To use a closure that gets the singleton instance:
register_activation_hook(KATAWP_PLUGIN_FILE, function() { KataWP::get_instance()->activate(); });

This properly calls the non-static activate() method on the KataWP singleton instance.